apiVersion: v1
kind: Service
metadata:
  name: {{ include "hapi-fhir-jpaserver.fullname" . }}
  labels:
    {{- include "hapi-fhir-jpaserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: fhir-api
      protocol: TCP
      name: fhir-api
  selector:
    {{- include "hapi-fhir-jpaserver.selectorLabels" . | nindent 4 }}
