skip-check:
  - CKV_SECRET_6
  - CKV_K8S_10
  - CKV_K8S_11
  - CKV_K8S_12
  - CKV_K8S_13
  - CKV_K8S_15
  - CKV_K8S_21
  - CKV_DOCKER_2
  - CKV_DOCKER_10
  - CKV2_K8S_6
  - CKV_K8S_35
  - CKV_K8S_38
  - CKV_K8S_31
  - CKV_K8S_29
