checks:
  cpuRequestsMissing: ignore
  cpuLimitsMissing: ignore
  memoryRequestsMissing: ignore
  memoryLimitsMissing: ignore
  pullPolicyNotAlways: ignore
  notReadOnlyRootFilesystem: warning
  privilegeEscalationAllowed: danger
  runAsPrivileged: danger
