---
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
ignorePaths:
  - ".gitignore"
words:
  - OHDSI
  - OMOP
  - chgl
  - kube
  - powertools
  - powerlint
  - fhir
  - kubernetes
  - broadsea
  - kubeadm
  - kubelet
  - synpuf
  - webapi
  - fullname
  - nindent
  - tolerations
  - whalesay
  - kubectl
  - jsonpath
  - tempdir
  - trunc
  - jdbc
  - initdb
  - psql
  - EOSQL
  - CREATEDB
  - DRIVERCLASSNAME
  - AUTHENTICATIONQUERY
  - PGHOST
  - PGPORT
  - PGUSER
  - PGDATABASE
  - PGPASSWORD
  - PGOPTIONS
  - DATASOURCE
  - TABLEPREFIX
  - OHDSISCHEMA
  - backoff
  - isready
  - firstname
  - middlename
  - lastname
  - Minikube
  - CLIENTID
  - APISECRET
  - LOGOUTURL
  - REDIRECTURL
  - Bitnami
  - CEST
  - subchart
  - POSTINIT
  - Keycloak
  - mkdir
  - Tsdtb
  - artifacthub
  - mssql
  - mymssql
  - Hyperscale
  - DATABASEPASSWORD
  - hadolint
  - xzvf
  - WORKDIR
  - vocabs
  - STORAGECLASS
  - restabs
  - CDMV
  - dbservicename
  - sapassword
  - healthcareapis
  - mssqldb
  - aadpodidbinding
  - aadpodidentity
  - ASPNETCORE
  - FORWARDEDHEADERS
  - DATABASESERVERNAME
  - DATABASENAME
  - DATABASEUSERNAME
  - DATABASESERVERPORT
  - jpaserver
  - FHIRSERVERURL
  - FHIRSERVERNAME
  - FETCHINTERVALSECONDS
  - hapi
  - bzrignore
  - hgignore
  - tmproj
  - kubeconform
  - maxdepth
  - lintconf
  - stefanzweifel
