apiVersion: v2
name: ohdsi
description: A Helm chart for deploying the OHDSI stack consisting of Atlas, WebAPI, and Achilles as a cron job.
type: application
home: https://github.com/OHDSI
keywords:
  - ohdsi
  - health care
  - research
sources:
  - https://github.com/OHDSI/Atlas
  - https://github.com/OHDSI/WebAPI
  - https://github.com/OHDSI/Broadsea-Achilles
maintainers:
  - name: chgl
dependencies:
  - name: postgresql
    version: 11.8.1
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
icon: https://avatars.githubusercontent.com/u/6570077
deprecated: false
kubeVersion: ">= 1.19.0"
version: 0.18.0
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
  artifacthub.io/recommendations: |
    - https://artifacthub.io/packages/helm/bitnami/postgresql
  artifacthub.io/links: |
    - name: OHDSI homepage
      url: https://www.ohdsi.org/
  artifacthub.io/changes: |-
    # When using the list of objects option the valid supported kinds are
    # added, changed, deprecated, removed, fixed and security.
    - kind: changed
      description: added optional job to load cohort definitions when installing the chart
