apiVersion: v2
name: ohdsi
description: A Helm chart for deploying the OHDSI stack consisting of Atlas, WebAPI, and Achilles as a cron job.
type: application
home: https://github.com/OHDSI
keywords:
  - ohdsi
  - health care
  - research
sources:
  - https://github.com/OHDSI/Atlas
  - https://github.com/OHDSI/WebAPI
  - https://github.com/OHDSI/Broadsea-Achilles
maintainers:
  - name: chgl
dependencies:
  - name: postgresql
    version: 11.6.12
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
# assumes that the ohdsi/webapi and ohdsi/atlas are released using the same version roughly at the same time
# if this doesn't work out, we'll need to specify them in the values.yaml again.
# renovate: datasource=docker depName=OHDSI/WebAPI
appVersion: 2.11.1
version: 0.17.11
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/changes: |
    # When using the list of objects option the valid supported kinds are
    # added, changed, deprecated, removed, fixed and security.
    - kind: changed
      description: updated WebAPI and ATLAS to version 2.11.1
