apiVersion: v2
name: ohdsi
description: A Helm chart for deploying OHDSI ATLAS and WebAPI.
type: application
home: https://github.com/OHDSI
keywords:
  - ohdsi
  - health care
  - research
sources:
  - https://github.com/OHDSI/Atlas
  - https://github.com/OHDSI/WebAPI
  - https://github.com/OHDSI/Achilles
maintainers:
  - name: chgl
dependencies:
  - name: postgresql
    version: 10.7.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: |
    # When using the list of objects option the valid supported kinds are added,
    # changed, deprecated, removed, fixed and security.
    - kind: removed
      description: |
        Removed Helm post-install hook annotation from CDM init Job due to timeout concerns for long-running init jobs
version: 0.6.1
