apiVersion: v2
name: ohdsi
description: A Helm chart for deploying OHDSI ATLAS and WebAPI.
type: application
home: https://github.com/OHDSI
keywords:
  - ohdsi
  - health care
  - research
sources:
  - https://github.com/OHDSI/Atlas
  - https://github.com/OHDSI/WebAPI
  - https://github.com/OHDSI/Achilles
maintainers:
  - name: chgl
dependencies:
  - name: postgresql
    version: 10.7.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Annotated the CDM init Job to run as a Helm post-install hook
      links:
        - name: GitHub Issue
          url: https://github.com/chgl/charts/issues/126
version: 0.6.0
