apiVersion: v2
name: ohdsi
description: A Helm chart for deploying the OHDSI stack consisting of Atlas, WebAPI, and Achilles as a cron job.
type: application
home: https://github.com/OHDSI
keywords:
  - ohdsi
  - health care
  - research
sources:
  - https://github.com/OHDSI/Atlas
  - https://github.com/OHDSI/WebAPI
  - https://github.com/OHDSI/Broadsea-Achilles
maintainers:
  - name: chgl
dependencies:
  - name: postgresql
    version: 16.0.5
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 2.26.0
icon: https://avatars.githubusercontent.com/u/6570077
deprecated: false
kubeVersion: ">= 1.19.0"
version: 0.24.14
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/bitnami/postgresql
  artifacthub.io/links: |
    - name: OHDSI Homepage
      url: https://www.ohdsi.org/
  artifacthub.io/screenshots: |
    - title: Defining a cohort in OHDSI ATLAS
      url: https://ohdsi.github.io/TheBookOfOhdsi/images/OhdsiAnalyticsTools/atlas.png
    - title: OHDSI ACHILLES Dashboard
      url: https://www.ohdsi.org/wp-content/uploads/2020/06/Screen-Shot-2020-06-01-at-3.31.29-PM.png
  artifacthub.io/changes: |-
    # When using the list of objects option the valid supported kinds are
    # added, changed, deprecated, removed, fixed and security.
    - kind: changed
      description: "Updated docker.io/bitnami/postgresql to 17.0.0-debian-12-r6"
