apiVersion: v2
name: ohdsi
description: A Helm chart for deploying the OHDSI stack consisting of Atlas, WebAPI, and Achilles as a cron job.
type: application
home: https://github.com/OHDSI
keywords:
  - ohdsi
  - health care
  - research
sources:
  - https://github.com/OHDSI/Atlas
  - https://github.com/OHDSI/WebAPI
  - https://github.com/OHDSI/Broadsea-Achilles
maintainers:
  - name: chgl
dependencies:
  - name: postgresql
    version: 11.9.8
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
icon: https://avatars.githubusercontent.com/u/6570077
deprecated: false
kubeVersion: ">= 1.19.0"
version: 0.19.0
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/bitnami/postgresql
  artifacthub.io/links: |
    - name: OHDSI Homepage
      url: https://www.ohdsi.org/
  artifacthub.io/screenshots: |
    - title: Defining a cohort in OHDSI ATLAS
      url: https://www.ohdsi.org/wp-content/uploads/2020/06/ATLAS.png
    - title: OHDSI ACHILLES Dashboard
      url: https://www.ohdsi.org/wp-content/uploads/2020/06/Screen-Shot-2020-06-01-at-3.31.29-PM.png
  artifacthub.io/changes: |-
    # When using the list of objects option the valid supported kinds are
    # added, changed, deprecated, removed, fixed and security.
    - kind: changed
      description: "updated postgresql chart to 11.9.8"
    - kind: changed
      description: updated WebAPI and ATLAS to v2.12.0
    - kind: added
      description: support for scraping prometheus metrics exposed by the OpenTelemetry Java Agent
      links:
        - name: GitHub PR
          url: https://github.com/OHDSI/WebAPI/pull/2082
    - kind: added
      description: support for distributed tracing via the OpenTelemetry Java Agent
      links:
        - name: GitHub PR
          url: https://github.com/OHDSI/WebAPI/pull/2082
