# Default values for atlas.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

global:
  postgresql:
    # name of an existing secret containing the following keys and passwords:
    # `postgresql-password`, `repmgr-password`, `admin-password`
    existingSecret: ""
    database: "ohdsi"
postgresqlha:
  enabled: true
  postgresqlImage:
    tag: 13.1.0

webApi:
  enabled: true
  replicaCount: 1
  image:
    registry: ghcr.io
    repository: chgl/ohdsi/webapi
    tag: 2.8.0-snapshot
    pullPolicy: Always

  # these values are ignored if `postgresqlha.enabled=true`
  db:
    host: "db"
    port: 5432
    database: "ohdsi"
    username: "postgres"
    password: "postgres"
    # name of an existing secret containing the password to the DB.
    # The key for the password has to be `postgresql-password`
    existingSecret: ""

  podAnnotations: {}

  podSecurityContext:
    {}
    # fsGroup: 2000

  securityContext:
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 101

  service:
    type: ClusterIP
    port: 8080

  ingress:
    enabled: false
    annotations:
      {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths: ["/WebAPI"]
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  resources:
    {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  readinessProbe:
    failureThreshold: 5
    initialDelaySeconds: 45
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 15
  # currentyl disabled due to the potentially large time the migration may take
  # we can use startupProbe starting in k8s 1.20
  # livenessProbe:
  #   failureThreshold: 5
  #   initialDelaySeconds: 30
  #   periodSeconds: 15
  #   successThreshold: 1
  #   timeoutSeconds: 15

  nodeSelector: {}

  tolerations: []

  affinity: {}

  # extra environment variables
  extraEnv:
    []
    # - name: "TEST"
    #   value: "TEST"

atlas:
  enabled: true
  replicaCount: 1
  image:
    registry: ghcr.io
    repository: chgl/ohdsi/atlas
    tag: 2.8.0
    pullPolicy: Always

  # the base URL of the OHDSI WebAPI, e.g. https://example.com/WebAPI
  # if this value is not set but `webapi.ingress.enabled=true`, then this
  # URL is constructed from `webapi.ingress`
  webApiUrl: ""

  podAnnotations: {}

  podSecurityContext:
    {}
    # fsGroup: 2000

  securityContext:
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    runAsUser: 101

  service:
    type: ClusterIP
    port: 8080

  ingress:
    enabled: false
    annotations:
      {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths: ["/atlas"]
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  resources:
    {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  readinessProbe:
    failureThreshold: 5
    initialDelaySeconds: 30
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 15
  livenessProbe:
    failureThreshold: 5
    initialDelaySeconds: 30
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 15

  nodeSelector: {}

  tolerations: []

  affinity: {}

  # extra environment variables
  extraEnv:
    []
    # - name: "TEST"
    #   value: "TEST"
