apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pathling-server.fullname" . }}
  labels:
    {{- include "pathling-server.labels" . | nindent 4 }}
  annotations:
    polaris.fairwinds.com/automountServiceAccountToken-exempt: "true"
    {{- with .Values.deploymentAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pathling-server.matchLabels" . | nindent 6 }}
  {{- if .Values.deployment.updateStrategy }}
  strategy: {{- toYaml .Values.deployment.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
        {{- if .Values.spark.cluster.executor.podTemplate }}
        checksum/config: {{ include (print $.Template.BasePath "/spark-pod-templates-cm.yaml") $ | sha256sum | quote }}
        {{- end }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "pathling-server.matchLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "pathling-server.serviceAccountName" . }}
      automountServiceAccountToken: {{ or .Values.serviceAccount.automountServiceAccountToken .Values.spark.cluster.enabled }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.minio.enabled }}
      initContainers:
        - name: wait-for-minio
          image: "{{ .Values.curl.image.registry }}/{{ .Values.curl.image.repository }}:{{ .Values.curl.image.tag }}"
          imagePullPolicy: "IfNotPresent"
          {{- with .Values.restrictedContainerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if $.Values.initContainers.resources }}
          resources: {{- toYaml $.Values.initContainers.resources | nindent 12 }}
          {{- else if ne $.Values.initContainers.resourcesPreset "none" }}
          resources: {{- include "common.resources.preset" (dict "type" $.Values.initContainers.resourcesPreset) | nindent 12 }}
          {{- end }}
          env:
            - name: MINIO_ENDPOINT_URL
              value: {{ template "pathling-server.s3Endpoint" . }}
            - name: MINIO_UPDATE
              value: "off"
          command: ["/bin/sh", "-c"]
          args:
            - |
              until [ "$(curl -s -o /dev/null -L -w '%{http_code}' "$MINIO_ENDPOINT_URL/minio/health/live")" == "200" ]; do
                echo "$(date): Waiting for minio server @ ${MINIO_ENDPOINT_URL} to be up";
                sleep 15;
              done;
      {{- end }}
      containers:
        - name: pathling-server
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- include "pathling-server.tplvalues.render" (dict "value" (omit .Values.livenessProbe "enabled") "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- include "pathling-server.tplvalues.render" (dict "value" (omit .Values.readinessProbe "enabled") "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            {{- include "pathling-server.tplvalues.render" (dict "value" (omit .Values.startupProbe "enabled") "context" $) | nindent 12 }}
          {{- end }}
          env:
            - name: MANAGEMENT_ENDPOINT_HEALTH_PROBES_ADD_ADDITIONAL_PATHS
              value: "true"
            - name: pathling.storage.warehouseUrl
              value: "{{ .Values.warehouse.url }}"
            - name: fs.s3a.endpoint
              value: "{{ include "pathling-server.s3Endpoint" . }}"
            - name: fs.s3a.aws.credentials.provider
              value: "org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider"
            - name: fs.s3a.access.key
              valueFrom:
                secretKeyRef:
                  name: {{ include "pathling-server.s3CredentialsSecretName" . }}
                  key: {{ include "pathling-server.s3AccessKeySecretKey" . }}
            - name: fs.s3a.secret.key
              valueFrom:
                secretKeyRef:
                  name: {{ include "pathling-server.s3CredentialsSecretName" . }}
                  key: {{ include "pathling-server.s3SecretKeySecretKey" . }}
            - name: fs.s3a.impl
              value: "org.apache.hadoop.fs.s3a.S3AFileSystem"
            - name: fs.s3a.path.style.access
              value: "true"

            {{- if .Values.spark.cluster.enabled }}
            - name: spark.master
              value: {{ .Values.spark.cluster.masterUrl }}
            - name: spark.driver.host
              value: {{ include "pathling-server.fullname" . }}-spark-driver
            - name: spark.driver.port
              value: "7077"
            - name: spark.blockManager.port
              value: "7078"
            - name: spark.driver.bindAddress
              value: "0.0.0.0"
            - name: spark.kubernetes.namespace
              value: {{ .Release.Namespace }}
            - name: spark.kubernetes.executor.container.image
              value: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            # <https://spark.apache.org/docs/latest/running-on-kubernetes.html#client-mode-executor-pod-garbage-collection>
            - name: spark.kubernetes.driver.pod.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: spark.ui.prometheus.enabled
              value: "true"
            - name: spark.executor.instances
              value: {{ .Values.spark.cluster.executor.instances | quote }}
            - name: spark.kubernetes.executor.podNamePrefix
              value: {{ include "pathling-server.fullname" . | quote }}
            {{- with .Values.spark.cluster.executor.memory }}
            - name: spark.executor.memory
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.spark.cluster.executor.request.cores }}
            - name: spark.kubernetes.executor.request.cores
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.spark.cluster.executor.limit.cores }}
            - name: spark.kubernetes.executor.limit.cores
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.spark.cluster.executor.request.memory }}
            - name: spark.kubernetes.executor.request.memory
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.spark.cluster.executor.limit.memory }}
            - name: spark.kubernetes.executor.limit.memory
              value: {{ . | quote }}
            {{- end }}

            {{- if .Values.spark.cluster.executor.podTemplate }}
            - name: spark.kubernetes.executor.podTemplateFile
              value: file:///tmp/spark-templates/executor-pod-template.yaml
            {{- end }}

            {{- end }}

            {{- if .Values.extraEnv }}
            {{- toYaml .Values.extraEnv | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: http-metrics
              containerPort: 8081
              protocol: TCP
            - name: http-spark-ui
              containerPort: 4040
              protocol: TCP
            - name: spark-driver
              containerPort: 7077
              protocol: TCP
            - name: spark-blck-mngr
              containerPort: 7078
              protocol: TCP
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- else if ne .Values.resourcesPreset "none" }}
          resources: {{- include "common.resources.preset" (dict "type" .Values.resourcesPreset) | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
            {{- if .Values.spark.cluster.executor.podTemplate }}
            - name: spark-executor-pod-template
              mountPath: /tmp/spark-templates/executor-pod-template.yaml
              readOnly: true
              subPath: executor-pod-template.yaml
            {{- end }}
            {{- if (.Values.warehouse.url | hasPrefix "file://") }}
            - name: data
              mountPath: {{ .Values.warehouse.url | trimPrefix "file://" }}
            {{- end }}
      volumes:
        - name: tmp-volume
        {{- if .Values.tmpVolume.persistence.enabled }}
          persistentVolumeClaim:
            claimName: "{{ include "pathling-server.fullname" . }}-tmp-data"
        {{- else }}
          emptyDir: {}
        {{- end }}
        {{- if .Values.spark.cluster.executor.podTemplate }}
        - name: spark-executor-pod-template
          configMap:
            name: {{ include "pathling-server.fullname" . }}-pod-templates
        {{- end }}
        {{- if (.Values.warehouse.url | hasPrefix "file://") }}
        {{- if .Values.warehouse.file.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: "{{ include "pathling-server.fullname" . }}-data"
        {{- else }}
        - name: data
          emptyDir: {}
        {{- end }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
