{{- if (not .Values.minio.enabled) -}}
{{- if (not .Values.warehouse.s3.credentials.existingSecret.name) -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "pathling-server.fullname" . }}-s3-credentials
  labels:
    {{- include "pathling-server.labels" . | nindent 4 }}
data:
  access-key: {{ .Values.warehouse.s3.credentials.accessKey | b64enc | quote }}
  secret-key: {{ .Values.warehouse.s3.credentials.secretKey | b64enc | quote }}
{{- end -}}
{{- end -}}
