apiVersion: v1
kind: Service
metadata:
  name: {{ include "pathling-server.fullname" . }}
  labels:
    {{- include "pathling-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.spark.ui.port }}
      targetPort: spark-ui-http
      protocol: TCP
      name: spark-ui-http
  selector:
    {{- include "pathling-server.matchLabels" . | nindent 4 }}
