{{- if .Values.spark.cluster.executor.podTemplate -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pathling-server.fullname" . }}-pod-templates
  labels:
    {{- include "pathling-server.labels" . | nindent 4 }}
data:
  executor-pod-template.yaml: |-
    {{ .Values.spark.cluster.executor.podTemplate | toYaml | nindent 4 }}
{{- end }}
