{{- if eq .Values.database.dataStore "SqlServer" }}
{{- $fullName := include "fhir-server.fullname" . -}}
apiVersion: azure.microsoft.com/v1beta1
kind: AzureSqlDatabase
metadata:
  name:  {{ $fullName }}
  labels:
    {{- include "fhir-server.labels" . | nindent 4 }}
spec:
  location: {{ .Values.database.location }}
  resourceGroup: {{ .Values.database.resourceGroup }}
  edition: {{ .Values.database.sql.edition }}
  server:  {{ $fullName }}
{{- end }}