{{- if eq .Values.database.dataStore "SqlServer" }}
{{- $fullName := include "fhir-server.fullname" . -}}
apiVersion: azure.microsoft.com/v1beta1
kind: AzureSqlFirewallRule
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "fhir-server.labels" . | nindent 4 }}
spec:
  resourceGroup: {{ .Values.database.resourceGroup }}
  server:  {{ $fullName }}
    
  # this IP range enables Azure Service access
  startIpAddress: 0.0.0.0
  endIpAddress: 0.0.0.0
{{- end }}