{{- if .Values.podIdentity.enabled -}}
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: {{ include "fhir-server.fullname" . }}
  labels:
    {{- include "fhir-server.labels" . | nindent 4 }}
spec:
  type: 0
  resourceID: {{ .Values.podIdentity.identityResourceId }}
  clientID: {{ .Values.podIdentity.identityClientId }}
{{- end }}