{{- if .Values.podIdentity.enabled -}}
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: {{ include "fhir-server.fullname" . }}-binding
spec:
  azureIdentity: {{ include "fhir-server.fullname" . }}
  selector: {{ include "fhir-server.fullname" . }}
{{- end }}