{{- if eq .Values.database.dataStore "CosmosDb" }}
{{- $fullName := include "fhir-server.fullname" . -}}
apiVersion: azure.microsoft.com/v1alpha1
kind: CosmosDB
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "fhir-server.labels" . | nindent 4 }}
spec:
  location: {{ .Values.database.location }}
  resourceGroup: {{ .Values.database.resourceGroup }}
  properties:
    databaseAccountOfferType: Standard
{{- end }}