{{- if and (eq .Values.database.dataStore "ExistingSqlServer") (not .Values.database.existingSqlServer.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fhir-server.fullname" . }}-existing-mssql
  labels:
    {{- include "fhir-server.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASEPASSWORD: {{ .Values.database.existingSqlServer.password | b64enc | quote}}
{{- end }}
