{{- if .Values.serviceMonitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fhir-server.fullname" . }}-metrics
  labels:
    {{- include "fhir-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.serviceMonitor.port }}
      targetPort: {{ .Values.serviceMonitor.port }}
      protocol: TCP
      name: metrics
  selector:
    {{- include "fhir-server.selectorLabels" . | nindent 4 }}
{{- end }}
