{{- if eq .Values.database.dataStore "SqlContainer" }}
{{- $fullName := include "fhir-server.fullname" . -}}
{{- $dbservicename := printf "%s-mssql" $fullName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $dbservicename }}
  labels:
    {{- include "fhir-server.labels" . | nindent 4 }}
type: Opaque
data:
  sapassword: {{ (printf "pW-%s-%s" (randNumeric 6) (randAlphaNum 16)) | b64enc | quote }}
{{- end }}
