{{- if eq .Values.database.dataStore "SqlContainer" }}
{{- $fullName := include "fhir-server.fullname" . -}}
{{- $dbservicename := printf "%s-mssql" $fullName }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:  
  name: {{ $dbservicename }}
  labels:
    {{- include "fhir-server.labels" . | nindent 4 }}
  {{- with .Values.database.sqlContainer.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  storageClassName: {{ .Values.database.sqlContainer.persistence.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.sqlContainer.persistence.size }}
{{- end }}