{{- if eq .Values.database.dataStore "SqlContainer" }}
{{- $fullName := include "fhir-server.fullname" . -}}
{{- $dbservicename := printf "%s-mssql" $fullName }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $dbservicename }}
  labels:
    {{- include "fhir-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.database.sqlContainer.port }}
      targetPort: 1433
      protocol: TCP
  selector:
    {{- include "fhir-server-mssql.selectorLabels" . | nindent 4 }}
{{- end }}
