apiVersion: v2
name: hapi-fhir-jpaserver
description: A Helm chart for deploying the HAPI FHIR JPA server starter on Kubernetes.
type: application
home: https://github.com/hapifhir/hapi-fhir-jpaserver-starter
sources:
  - https://github.com/hapifhir/hapi-fhir-jpaserver-starter
maintainers:
  - name: chgl
dependencies:
  - name: postgresql
    version: 10.7.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: |
        use Helm's new SubChart templating feature: https://github.com/helm/helm/pull/9957. Requires Helm 3.7+
  artifacthub.io/license: MIT
  artifacthub.io/prerelease: "true"
version: 0.5.0
