{{- if .Values.appsettings -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "magnifhir.fullname" . }}-appsettings
  labels:
    {{- include "magnifhir.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
data:
  appsettings.Production.json: |-
    {{ .Values.appsettings | nindent 4 }}
{{- end }}
