apiVersion: v1
kind: Service
metadata:
  name: {{ include "magnifhir.fullname" . }}
  labels:
    {{- include "magnifhir.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
    - port: {{ .Values.service.metrics.port }}
      targetPort: 8081
      protocol: TCP
      name: http-metrics
  selector:
    {{- include "magnifhir.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
