{{- if .Values.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "fhir-server-exporter.fullname" $ }}
  labels:
    {{- include "fhir-server-exporter.labels" $ | nindent 4 }}
    app.kubernetes.io/component: fhir-server-exporter
spec:
  podSelector:
    matchLabels:
      {{- include "fhir-server-exporter.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: fhir-server-exporter
  policyTypes:
    - Ingress
    - Egress
  ingress:
  {{- if .Values.networkPolicy.extraIngress }}
    {{- include "common.tplvalues.render" (dict "value" .Values.networkPolicy.extraIngress "context" .) | nindent 4 }}
  {{- end }}
  egress:
    # Allow DNS resolution
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
  {{- if .Values.networkPolicy.extraEgress }}
    {{- include "common.tplvalues.render" (dict "value" .Values.networkPolicy.extraEgress "context" .) | nindent 4 }}
  {{- end }}
{{- end }}
