apiVersion: v2
name: fhir-server
description: A Helm chart for deploying the Microsoft FHIR Server for Azure.
home: https://github.com/microsoft/fhir-server
keywords:
  - fhir
  - fhir-server
maintainers:
  - name: chgl
sources:
  - https://github.com/microsoft/fhir-server
type: application
version: 0.12.26
deprecated: false
dependencies:
  - name: common
    repository: oci://ghcr.io/chgl/charts
    version: 0.1.0
annotations:
  artifacthub.io/changes: |-
    # When using the list of objects option the valid supported kinds are
    # added, changed, deprecated, removed, fixed and security.
    - kind: changed
      description: "Updated mcr.microsoft.com/mssql/server to sha256:d24e4c2ba946e91ef4065fc2a2e43bc4cd3fadf1bd6feac4f5d8e4185aa98cac"
