apiVersion: v2
name: kubeclarity
appVersion: v2.22.0
description: Charts for KubeClarity deployment.
version: 0.1.3
home: https://github.com/openclarity/kubeclarity
icon: https://github.com/openclarity/kubeclarity/raw/main/images/kubeclarity-logo.png
sources:
  - https://github.com/openclarity/kubeclarity
maintainers:
  - name: KubeClarity
    url: https://github.com/openclarity/kubeclarity
type: application
dependencies:
  - name: postgresql
    version: "13.2.24"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: kubeclarity-postgresql.enabled
    alias: kubeclarity-postgresql
  - name: trivy
    version: "0.7.0"
    repository: https://aquasecurity.github.io/helm-charts
    condition: kubeclarity-trivy-server.enabled
    alias: kubeclarity-trivy-server
