postgresql:
  auth:
    postgresPassword: "postgres"
    database: "vfps"

podDisruptionBudget:
  enabled: true

replicaCount: 3

serviceMonitor:
  enabled: false

resources:
  limits:
    cpu: 1000m
    memory: 128Mi
  requests:
    cpu: 1000m
    memory: 128Mi

ingress:
  enabled: true

extraEnv:
  - name: "Pseudonymization__Caching__Namespaces__IsEnabled"
    value: "true"
  - name: "Pseudonymization__Caching__Namespaces__SizeLimit"
    value: "64"
  - name: "Pseudonymization__Caching__Namespaces__AbsoluteExpiration"
    value: "0.01:23:00"
