# -- number of replicas
replicaCount: 1

# @ignored
image:
  registry: ghcr.io
  repository: chgl/vfps
  tag: v1.0.0@sha256:3a6cf7c3140213dc2d6351693fb8306dc00503f57d51c2b2dc31bfeee99db5a7
  pullPolicy: IfNotPresent

migrationsJob:
  # -- whether to enable the database migration job. If enabled, a `ServiceAccount`, `Role`, and `RoleBinding` resources are created
  # which are used by an init container of the main application to wait for the migrations to complete.
  enabled: true
  # -- restart policy for the migration job
  restartPolicy: Never
  # -- extra environment variables to set on the migrations job container
  extraEnv: []

serviceMonitor:
  # -- if enabled, creates a ServiceMonitor instance for Prometheus Operator-based monitoring
  enabled: false
  # -- additional labels to apply to the ServiceMonitor object, e.g. `release: prometheus`
  additionalLabels: {}
  # namespace: monitoring
  # interval: 30s
  # scrapeTimeout: 10s

# -- image pull secrets used by the main deployment container
imagePullSecrets: []

# -- override the release name
nameOverride: ""

# -- override the full release name
fullnameOverride: ""

serviceAccount:
  # -- Specifies whether a service account should be created.
  create: false
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# -- annotations to set on the main deployment's pod
podAnnotations: {}

# -- the pod security context
podSecurityContext:
  {}
  # fsGroup: 2000

# @ignored
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
  seccompProfile:
    type: RuntimeDefault

service:
  # -- the type of service
  type: ClusterIP
  # -- the port for the main endpoint which supports HTTP1, HTTP2, and HTTP3
  port: 8080
  # -- the port which supports HTTP2 only, to accept plaintext gRPC calls
  grpcPort: 8081

ingress:
  # -- create an Ingress for the application
  enabled: false
  # -- ingressClassName to use
  className: ""
  # -- extra annotations to apply to the Ingress resource
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  # -- list of ingress hosts
  hosts:
    - host: vfps.127.0.0.1.nip.io
      paths:
        - path: /
          pathType: ImplementationSpecific
          portName: http
  # -- TLS configuration
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# -- resource limits and requests
resources:
  {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  # -- enable horizontal pod autoscaling
  enabled: false
  # -- minReplicas is the lower limit for the number of replicas to which the autoscaler can scale down.
  # It defaults to 1 pod. minReplicas is allowed to be 0 if the alpha feature gate HPAScaleToZero is
  # enabled and at least one Object or External metric is configured.
  # Scaling is active as long as at least one metric value is available.
  minReplicas: 1
  # -- upper limit for the number of pods that can be set by the autoscaler; cannot be smaller than `minReplicas`.
  maxReplicas: 5
  # -- target average CPU utilization (represented as a percentage of requested CPU)
  # over all the pods; if not specified the default autoscaling policy will be used.
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

podDisruptionBudget:
  # -- create a PodDisruptionBudget resource
  enabled: false
  # -- Minimum available instances; ignored if there is no PodDisruptionBudget
  minAvailable: 1
  # -- Maximum unavailable instances; ignored if there is no PodDisruptionBudget
  maxUnavailable: ""

# -- pod node selector
nodeSelector: {}

# -- pod tolerations
tolerations: []

# -- pod affinity
affinity: {}

# -- pod topology spread configuration
# see: <https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/#api>
topologySpreadConstraints:
  []
  # - maxSkew: 1
  #   topologyKey: topology.kubernetes.io/zone
  #   whenUnsatisfiable: ScheduleAnyway
  #   labelSelector:
  #     matchLabels:
  #       app.kubernetes.io/instance: vfps

# @ignored
waitForDatabaseInitContainer:
  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: 15.0.0-debian-11-r3@sha256:6ebd4468a91c35300c992c4c0ee10e13dfcccd928a5a3de5cd089d3a3bf19c1c
    pullPolicy: IfNotPresent

# -- container security context applied to init containers and the Helm test pods
# @ignored
restrictedContainerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  privileged: false
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  runAsUser: 65534
  runAsGroup: 65534
  seccompProfile:
    type: RuntimeDefault

database:
  # -- database hostname of an external database. Only used if `postgresql.enabled` is set to `false`.
  host: "host.example.com"
  # -- port used to connect to the postgres DB
  port: 5432
  # -- name of the database inside. If postgresql.enabled=true, then postgresql.postgresqlDatabase is used
  database: "vfps"
  # -- username used to connect to the DB. Note that this name is currently used even if postgresql.enabled=true
  username: "postgres"
  # -- the database password. Only used if postgresql.enabled=false, otherwise the secret created by the postgresql chart is used
  password: "postgres"
  # -- name of an existing secret containing the password to the DB.
  existingSecret: ""
  # -- name of the key in `webApi.db.existingSecret` to use as the password to the DB.
  existingSecretKey: "postgresql-postgres-password"
  # -- schema used for the tables.
  schema: "vfps"
  # -- additional parameters appended to the connection string
  additionalConnectionStringParameters: "Timeout=60;Max Auto Prepare=5;"

# -- extra environment variables to set on the vfps api container
extraEnv:
  []
  # - name: "Pseudonymization__Caching__Namespaces__IsEnabled"
  #   value: "true"
  # - name: "Pseudonymization__Caching__Namespaces__SizeLimit"
  #   value: "64"
  # - name: "Pseudonymization__Caching__Namespaces__AbsoluteExpiration"
  #   value: "0.01:23:00"

# @ignored
postgresql:
  enabled: true
  auth:
    database: vfps
  primary:
    containerSecurityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL

# @ignored
curl:
  image:
    registry: index.docker.io
    repository: curlimages/curl
    tag: 7.86.0@sha256:cfdeba7f88bb85f6c87f2ec9135115b523a1c24943976a61fbf59c4f2eafd78e
