postgresql:
  auth:
    postgresPassword: "postgres"
    database: "vfps"

podDisruptionBudget:
  enabled: true

replicaCount: 1

serviceMonitor:
  enabled: false

resources:
  limits:
    cpu: 1000m
    memory: 128Mi
  requests:
    cpu: 1000m
    memory: 128Mi

ingress:
  enabled: true
  hosts:
    - host: vfps.127.0.0.1.nip.io
      paths:
        - path: /
          pathType: ImplementationSpecific
    - host: vfps-grpc.127.0.0.1.nip.io
      paths:
        - path: /
          pathType: ImplementationSpecific
          portName: grpc

extraEnv:
  - name: "Pseudonymization__Caching__Namespaces__IsEnabled"
    value: "true"
  - name: "Pseudonymization__Caching__Namespaces__SizeLimit"
    value: "64"
  - name: "Pseudonymization__Caching__Namespaces__AbsoluteExpiration"
    value: "0.01:23:00"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
  # targetMemoryUtilizationPercentage: 80
