{{- $secretName := index .Values "kubeclarity-postgresql" "auth" "existingSecret" -}}
{{- if index .Values "kubeclarity-postgresql-external" "enabled" }}
  {{- $secretName = index .Values "kubeclarity-postgresql-external" "auth" "existingSecret" -}}
{{- end }}
{{- $secretKey := index .Values "kubeclarity-postgresql-secret" "secretKey" -}}
{{- $postgresPassword := .Values.global.databasePassword | b64enc -}}
{{- if (index .Values "kubeclarity-postgresql-secret" "create") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- include "kubeclarity.labels" . | nindent 4 }}
data:
  {{ $secretKey }}: {{ $postgresPassword }}
{{- end }}
