replicaCount: 1

ingress:
  enabled: true
  hosts:
    - host: pathling-server.127.0.0.1.nip.io
      paths:
        - path: /
          pathType: ImplementationSpecific
          portName: http

minio:
  ingress:
    enabled: true
    hostname: pathling-server-minio.127.0.0.1.nip.io
  apiIngress:
    enabled: true
    hostname: pathling-server-minio-api.127.0.0.1.nip.io

spark:
  cluster:
    enabled: true
