replicaCount: 1

ingress:
  enabled: true
  hosts:
    - host: pathling-server.127.0.0.1.nip.io
      paths:
        - path: /
          pathType: ImplementationSpecific
          portName: http

minio:
  ingress:
    enabled: true
    hosts:
      - host: minio.127.0.0.1.nip.io
        paths:
          - path: /
            pathType: Prefix
  consoleIngress:
    enabled: true
    hosts:
      - host: minio-console.127.0.0.1.nip.io
        paths:
          - path: /
            pathType: Prefix

spark:
  cluster:
    enabled: false
