# Default values for hapi-fhir-jpaserver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# the URL of the FHIR server whose metrics should be scraped. Interpreted as a template.
fhirServerUrl: ""

# the name of the FHIR server (included in the metrics as `server_name`). Interpreted as a template.
fhirServerName: ""

# FHIR server exporter fetch interval in seconds
fetchIntervalSeconds: 300

serviceMonitor:
  # if enabled, creates a ServiceMonitor instance for Prometheus Operator-based monitoring
  enabled: false
  # additional labels to apply to the ServiceMonitor object, e.g. `release: prometheus`
  additionalLabels: {}
  # namespace: monitoring
  # interval: 30s
  # scrapeTimeout: 10s

# number of replicas
replicaCount: 1

# the exporter image
image: # +doc-gen:ignore
  registry: ghcr.io
  repository: chgl/fhir-server-exporter
  tag: v2.1.5@sha256:8257849225e74656702c25fe0144f1239ba88d16b1fd6f8de8c6b2a16d864a07
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# annotations applied to the server deployment
deploymentAnnotations: {}

# annotations applied to the server pod
podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext: # +doc-gen:ignore
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
  seccompProfile:
    type: RuntimeDefault

service:
  type: ClusterIP
  port: 8080

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# readiness probe
readinessProbe: # +doc-gen:ignore
  failureThreshold: 5
  initialDelaySeconds: 30
  periodSeconds: 20
  successThreshold: 1
  timeoutSeconds: 20

# readiness probe
livenessProbe: # +doc-gen:ignore
  failureThreshold: 5
  initialDelaySeconds: 30
  periodSeconds: 20
  successThreshold: 1
  timeoutSeconds: 20

# extra env vars to set on the fhir-server-exporter container
extraEnv: []
# - name: "FOO"
#   value: "BAR"

# specify custom queries as a list of `name`, `query` and `description` objects.
# see <https://github.com/chgl/fhir-server-exporter#custom-queries> for details.
customQueries:
  []
  # - name: fhir_male_patient_count
  #   query: Patient?gender=male
  #   description: Male patients
  # - name: fhir_female_patient_count
  #   query: Patient?gender=female

# @ignored
curl: # +doc-gen:ignore
  image:
    registry: index.docker.io
    repository: curlimages/curl
    tag: 7.86.0@sha256:cfdeba7f88bb85f6c87f2ec9135115b523a1c24943976a61fbf59c4f2eafd78e
