apiVersion: v1
kind: Service
metadata:
  name: {{ include "vfps.fullname" . }}-headless
  labels:
    {{- include "vfps.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "vfps.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
