{{- if .Values.migrationsJob.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "vfps.fullname" . }}-view-migrations-job
  labels:
    {{- include "vfps.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrations
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    resourceNames: ["{{ include "vfps.migrationsJob.resourceName" . }}"]
    verbs: ["get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "vfps.fullname" . }}-view-migrations-job
  labels:
    {{- include "vfps.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrations
subjects:
  - kind: ServiceAccount
    name: {{ include "vfps.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "vfps.fullname" . }}-view-migrations-job
  apiGroup: rbac.authorization.k8s.io
{{- end }}
