{{- if (or .Values.serviceAccount.create .Values.migrationsJob.enabled) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vfps.serviceAccountName" . }}
  labels:
    {{- include "vfps.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
