appsettings: |-
  {
    "FhirServers": [
      {
        "Name": "HAPI FHIR JPA Server",
        "BaseUrl": "http://hapi-fhir-server.svc/fhir"
      }
    ]
  }

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 500m
    memory: 256Mi

ingress:
  enabled: true
