{{- with .Values.achilles }}
{{- if .enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "ohdsi.fullname" $ }}-achilles-cron
  labels:
    {{- include "ohdsi.labels" $ | nindent 4 }}
    app.kubernetes.io/name: {{ include "ohdsi.name" $ }}-achilles-cron
    app.kubernetes.io/instance: {{ $.Release.Name }}-achilles-cron
  {{- with $.Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  schedule: {{ .schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          {{- with $.Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .podSecurityContext}}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - name: achilles-cron
              image: "{{ .image.registry }}/{{ .image.repository }}:{{ .image.tag }}"
              imagePullPolicy: {{ .image.pullPolicy }}
              {{- with .securityContext}}
              securityContext:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with .resources}}
              resources:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              env:
                - name: ACHILLES_DB_URI
                  value: {{ include "ohdsi.achilles.dbUrl" $ }}
                - name: ACHILLES_DB_USERNAME
                  value: {{ include "ohdsi.database.user" $ }}
                - name: ACHILLES_DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "ohdsi.webapi.db-secret-name" $ }}
                      {{- if $.Values.webApi.db.existingSecret }}
                      key: {{ $.Values.webApi.db.existingSecretKey }}
                      {{- else }}
                      key: "postgresql-password"
                      {{- end }}
                - name: ACHILLES_CDM_SCHEMA
                  value: {{ .schemas.cdm | quote }}
                - name: ACHILLES_VOCAB_SCHEMA
                  value: {{ .schemas.vocab | quote }}
                - name: ACHILLES_RES_SCHEMA
                  value: {{ .schemas.res | quote }}
                - name: ACHILLES_CDM_VERSION
                  value: {{ .cdmVersion | quote }}
                - name: ACHILLES_SOURCE
                  value: {{ .sourceName | quote }}
                {{- if .extraEnv }}
                {{- toYaml .extraEnv | nindent 16 }}
                {{- end }}
{{- end }}
{{- end }}
