{{- with .Values.achilles }}
{{- if .enabled }}
apiVersion: {{ include "ohdsi.cronJob.apiVersion" $ }}
kind: CronJob
metadata:
  name: {{ include "ohdsi.fullname" $ }}-achilles-cron
  labels:
    {{- include "ohdsi.labels" $ | nindent 4 }}
    app.kubernetes.io/component: achilles-cron
  {{- with $.Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  schedule: {{ .schedule | quote }}
  successfulJobsHistoryLimit: {{ .successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .failedJobsHistoryLimit }}
  concurrencyPolicy: {{ .concurrencyPolicy }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "ohdsi.labels" $ | nindent 12 }}
            app.kubernetes.io/component: achilles-cron
          {{- with .podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          restartPolicy: Never
          {{- with $.Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .podSecurityContext}}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "ohdsi.achilles.serviceAccountName" $ }}
          automountServiceAccountToken: {{ .serviceAccount.automountServiceAccountToken }}
          containers:
            - name: achilles-cron
              image: "{{ .image.registry }}/{{ .image.repository }}:{{ .image.tag }}"
              imagePullPolicy: {{ .image.pullPolicy }}
              {{- with .securityContext}}
              securityContext:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- if .resources }}
              resources: {{- toYaml .resources | nindent 16 }}
              {{- else if ne .resourcesPreset "none" }}
              resources: {{- include "common.resources.preset" (dict "type" .resourcesPreset) | nindent 16 }}
              {{- end }}
              volumeMounts:
                - mountPath: /opt/achilles/workspace
                  name: achilles-workspace-volume
                - mountPath: /tmp
                  name: r-tempdir-volume
              env:
                - name: ACHILLES_DB_URI
                  value: {{ include "ohdsi.achilles.dbUrl" $ }}
                - name: ACHILLES_DB_USERNAME
                  value: {{ include "ohdsi.database.user" $ }}
                - name: ACHILLES_DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "ohdsi.webapi.db-secret-name" $ }}
                      key: {{ include "ohdsi.webapi.db-secret-key" $ }}
                - name: ACHILLES_CDM_SCHEMA
                  value: {{ .schemas.cdm | quote }}
                - name: ACHILLES_VOCAB_SCHEMA
                  value: {{ .schemas.vocab | quote }}
                - name: ACHILLES_RES_SCHEMA
                  value: {{ .schemas.res | quote }}
                - name: ACHILLES_CDM_VERSION
                  value: {{ .cdmVersion | quote }}
                - name: ACHILLES_SOURCE
                  value: {{ .sourceName | quote }}
                {{- if .extraEnv }}
                {{- toYaml .extraEnv | nindent 16 }}
                {{- end }}
          volumes:
            - name: achilles-workspace-volume
              emptyDir: {}
            - name: r-tempdir-volume
              emptyDir: {}
{{- end }}
{{- end }}
