{{- with .Values.atlas }}
{{- if .enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ohdsi.fullname" $ }}-atlas
  labels:
    {{- include "ohdsi.labels" $ | nindent 4 }}
    app.kubernetes.io/component: atlas
spec:
  type: {{ .service.type }}
  ports:
    - port: {{ .service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ohdsi.matchLabels" $ | nindent 4 }}
    app.kubernetes.io/component: atlas
{{- end }}
{{- end }}
