{{- with .Values.atlas }}
{{- if .podDisruptionBudget.enabled }}
kind: PodDisruptionBudget
apiVersion: policy/v1
metadata:
  name: {{ include "ohdsi.fullname" $ }}-atlas
  labels:
    {{- include "ohdsi.labels" $ | nindent 4 }}
    app.kubernetes.io/component: atlas
spec:
  {{- if .podDisruptionBudget.minAvailable }}
  minAvailable: {{ .podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ohdsi.matchLabels" $ | nindent 6 }}
      app.kubernetes.io/component: atlas
{{- end }}
{{- end }}
