{{- if .Values.atlas.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ohdsi.fullname" $ }}-atlas
  labels:
    {{- include "ohdsi.labels" . | nindent 4 }}
  {{- with .Values.atlas.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
