{{- with .Values.cdmInitJob }}
{{- if .enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ohdsi.fullname" $ }}-cdm-init
  labels:
    {{- include "ohdsi.labels" $ | nindent 4 }}
    app.kubernetes.io/name: {{ include "ohdsi.name" $ }}-cdm-init
    app.kubernetes.io/instance: {{ $.Release.Name }}-cdm-init
  {{- with $.Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  backoffLimit: 4
  template:
    metadata:
    {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "ohdsi.name" $ }}-cdm-init
        app.kubernetes.io/instance: {{ $.Release.Name }}-cdm-init
    spec:
      restartPolicy: Never
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: cdm-init
          image: "{{ .image.registry }}/{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "ohdsi.webapi.db-secret-name" $ }}
                  {{- if $.Values.webApi.db.existingSecret }}
                  key: {{ $.Values.webApi.db.existingSecretKey }}
                  {{- else }}
                  key: "postgresql-password"
                  {{- end }}
            - name: PGUSER
              value: {{ include "ohdsi.database.user" $ | quote }}
            - name: PGHOST
              value: {{ include "ohdsi.database.host" $ | quote }}
            - name: PGPORT
              value: {{ include "ohdsi.database.port" $ | quote }}
            - name: PGDATABASE
              value: {{ include "ohdsi.database.name" $ | quote }}
            - name: WEBAPI_URL
            {{- if $.Values.atlas.webApiUrl }}
              value: {{ $.Values.atlas.webApiUrl }}
            {{- else }}
              value: "http://{{ include "ohdsi.fullname" $ }}-webapi:{{ $.Values.webApi.service.port }}/WebAPI"
            {{- end }}
            {{- if .extraEnv }}
            {{- toYaml .extraEnv | nindent 12 }}
            {{- end }}
{{- end }}
{{- end }}
