{{- with .Values.cdmInitJob }}
{{- if .enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ohdsi.fullname" $ }}-cdm-init
  labels:
    {{- include "ohdsi.labels" $ | nindent 4 }}
    app.kubernetes.io/component: cdm-init
  {{- with .annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $.Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  backoffLimit: {{ .backoffLimit }}
  {{- with .ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ . }}
  {{- end }}
  template:
    metadata:
    {{- with .podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "ohdsi.labels" $ | nindent 8 }}
        app.kubernetes.io/component: cdm-init
    spec:
      restartPolicy: {{ .restartPolicy }}
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: cdm-init
          image: "{{ .image.registry }}/{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          {{- with .securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "ohdsi.webapi.db-secret-name" $ }}
                  key: {{ include "ohdsi.webapi.db-secret-key" $ }}
            - name: PGUSER
              value: {{ include "ohdsi.database.user" $ | quote }}
            - name: PGHOST
              value: {{ include "ohdsi.database.host" $ | quote }}
            - name: PGPORT
              value: {{ include "ohdsi.database.port" $ | quote }}
            - name: PGDATABASE
              value: {{ include "ohdsi.database.name" $ | quote }}
            - name: WEBAPI_URL
              value: {{ include "ohdsi.webApi.url" $ }}
            {{- if .extraEnv }}
            {{- toYaml .extraEnv | nindent 12 }}
            {{- end }}
{{- end }}
{{- end }}
