{{- if .Values.webApi.enabled }}
{{- if (not .Values.webApi.auth.openid.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ohdsi.fullname" . }}-webapi-auth
  labels:
    {{- include "ohdsi.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "ohdsi.name" . }}-webapi-auth
    app.kubernetes.io/instance: {{ .Release.Name }}-webapi-auth
type: Opaque
data:
  webapi-openid-client-secret: {{ .Values.webApi.auth.openid.clientSecret | b64enc | quote }}
{{- end -}}
{{- end -}}
