{{- if (and .Values.webApi.enabled .Values.webApi.auth.openid.enabled )}}
{{- if (not .Values.webApi.auth.openid.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ohdsi.fullname" . }}-webapi-auth
  labels:
    {{- include "ohdsi.labels" . | nindent 4 }}
    app.kubernetes.io/component: webapi
type: Opaque
data:
  webapi-openid-client-secret: {{ .Values.webApi.auth.openid.clientSecret | b64enc | quote }}
{{- end -}}
{{- end -}}
