{{- if .Values.webApi.enabled }}
{{- if and (not .Values.postgresql.enabled) (not .Values.webApi.db.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ohdsi.fullname" . }}-webapi-db-secret
  labels:
    {{- include "ohdsi.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "ohdsi.name" . }}-webapi-db-secret
    app.kubernetes.io/instance: {{ .Release.Name }}-webapi-db-secret
type: Opaque
data:
  postgresql-password: {{ .Values.webApi.db.password | b64enc | quote }}
{{- end -}}
{{- end -}}
