{{- with .Values.webApi }}
{{- if .podDisruptionBudget.enabled }}
kind: PodDisruptionBudget
apiVersion: policy/v1
metadata:
  name: {{ include "ohdsi.fullname" $ }}-webapi
  labels:
    {{- include "ohdsi.labels" $ | nindent 4 }}
    app.kubernetes.io/name: {{ include "ohdsi.name" $ }}-webapi
    app.kubernetes.io/instance: {{ $.Release.Name }}-webapi
spec:
  {{- if .podDisruptionBudget.minAvailable }}
  minAvailable: {{ .podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ohdsi.name" $ }}-webapi
      app.kubernetes.io/instance: {{ $.Release.Name }}-webapi
{{- end }}
{{- end }}
