{{- with .Values.webApi }}
{{- if .enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ohdsi.fullname" $ }}-webapi
  labels:
    {{- include "ohdsi.labels" $ | nindent 4 }}
    app.kubernetes.io/component: webapi
spec:
  type: {{ .service.type }}
  ports:
    - port: {{ .service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ohdsi.matchLabels" $ | nindent 4 }}
    app.kubernetes.io/component: webapi
{{- end }}
{{- end }}
