name: Lint and Test Charts

on:
  pull_request:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v2.0.3

  lint:
    needs:
      - pre-commit
    runs-on: ubuntu-20.04
    container: ghcr.io/chgl/kube-powertools:v1.16.7
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if documentation is up-to-date
        run: generate-docs.sh && git diff --exit-code HEAD

      - name: Update dependencies
        run: find charts/ ! -path charts/ -maxdepth 1 -type d -exec helm dependency update {} \;

      - name: Run YAML lint
        run: yamllint .

      - name: Run chart-testing (lint)
        run: ct lint --config .github/ct/ct.yaml

      - name: Cache kubeconform schemas
        id: cache-powerlint-kubeconform
        uses: actions/cache@v2
        with:
          path: /tmp
          key: ${{ runner.os }}-powerlint-kubeconform

      - name: Run Powerlint
        env:
          KUBERNETES_VERSIONS: "1.19.0 1.20.0 1.21.0 1.22.0 1.23.0"
        run: chart-powerlint.sh

      # used to test whether the changelog generation process works
      - name: Generate changelogs (test)
        run: generate-chart-changelog.sh

  test:
    runs-on: ubuntu-20.04
    needs:
      - lint
    strategy:
      matrix:
        k8s-version: [1.21.10, 1.22.7, 1.23.4]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
        if: steps.list-changed.outputs.changed == 'true'
        with:
          cluster_name: kind-cluster-k8s-${{ matrix.k8s-version }}
          node_image: kindest/node:v${{ matrix.k8s-version }}

      - name: Run chart-testing (install)
        run: ct install --config .github/ct/install.yaml
