name: Lint and Test Charts

on:
  pull_request:
    branches: [master]

permissions:
  contents: read

# https://stackoverflow.com/a/72408109
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  lint:
    runs-on: ubuntu-24.04
    container: ghcr.io/chgl/kube-powertools:v2.4.18@sha256:329353558cdc6af6c0b93172b36498cfea07a07b37af90df6eaf8457ca1eec31
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit # change to 'egress-policy: block' after couple of runs
          disable-sudo: true
          disable-telemetry: true

      - name: Add workspace as safe directory
        run: |
          git config --global --add safe.directory /__w/charts/charts

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      # via <https://github.com/helm/chart-testing/issues/577>
      - run: |
          git branch "master" "origin/master"

      - name: Check if documentation is up-to-date
        run: |
          generate-docs.sh
          if git diff --exit-code HEAD; then
            echo -e "\033[0;32mDocumentation up to date\033[0m ✔"
          else
            echo -e "\033[0;31mDocumentation outdated! Please run generate-docs.sh locally and push the changes.\033[0m ❌"
            git diff --color
            exit 1
          fi

      - name: Update dependencies
        run: find charts/ ! -path charts/ -maxdepth 1 -type d -exec helm dependency update {} \;

      - name: Run YAML lint
        run: yamllint .

      - name: Run chart-testing (lint)
        run: ct lint --config .github/ct/ct.yaml

      - name: Run ArtifactHub lint
        run: ah lint --kind=helm

      - name: Cache kubeconform schemas
        id: cache-powerlint-kubeconform
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: /tmp
          key: ${{ runner.os }}-powerlint-kubeconform

      - name: Run Powerlint
        env:
          KUBERNETES_VERSIONS: "1.31.0 1.32.0 1.33.0"
        run: chart-powerlint.sh

      # used to test whether the changelog generation process works
      - name: Generate changelogs (test)
        run: generate-chart-changelog.sh

      # used to test whether the kubescape reports generation works
      # otherwise it is only run in the release job
      - name: Generate kubescape reports
        run: |
          kubescape scan framework AllControls --keep-local --format=html --output=kubescape-reports/allcontrols.html charts/

  test:
    runs-on: ubuntu-24.04
    needs:
      - lint
    strategy:
      matrix:
        k8s-version: [1.31.9, 1.32.5, 1.33.2]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit # change to 'egress-policy: block' after couple of runs
          disable-sudo: true
          disable-telemetry: true

      - name: Add workspace as safe directory
        run: |
          git config --global --add safe.directory /__w/charts/charts

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      # after some trying, we can't simply use the kube-powertools container and its included ct.
      # the latest problem is that the kubectl inside the container can't access the kind cluster created on the host:
      # err="couldn't get current server API group list: Get \"https://127.0.0.1:37679/api?timeout=30s\": dial tcp 127.0.0.1:37679: connect: connection refused"
      # it might work if we override the api host to the host.docker.internal address.
      - name: Set up chart-testing
        uses: helm/chart-testing-action@0d28d3144d3a25ea2cc349d6e59901c4ff469b3b # v2.7.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        shell: bash
        run: |
          changed=$(ct list-changed --config .github/ct/install.yaml)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "${GITHUB_OUTPUT}"
          fi

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
        if: ${{steps.list-changed.outputs.changed == 'true'}}
        with:
          cluster_name: kind-cluster-k8s-${{ matrix.k8s-version }}
          node_image: kindest/node:v${{ matrix.k8s-version }}

      - name: Run chart-testing (install)
        if: ${{steps.list-changed.outputs.changed == 'true'}}
        run: ct install --config .github/ct/install.yaml
