name: Lint and Test Charts

on:
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-22.04
    container: ghcr.io/chgl/kube-powertools:v1.19.0@sha256:ac3f3139af1a807a585521b7e2707b03f62411064b8fc03626c5941c2555b9a2
    steps:
      - name: Add workspace as safe directory
        run: |
          git config --global --add safe.directory /__w/charts/charts

      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
        with:
          fetch-depth: 0

      - name: Check if documentation is up-to-date
        run: |
          generate-docs.sh
          if git diff --exit-code HEAD; then
            echo -e "\033[0;32mDocumentation up to date\033[0m ✔"
          else
            echo -e "\033[0;31mDocumentation outdated! Please run generate-docs.sh locally and push the changes.\033[0m ❌"
            git diff --color
            exit 1
          fi

      - name: Update dependencies
        run: find charts/ ! -path charts/ -maxdepth 1 -type d -exec helm dependency update {} \;

      - name: Run YAML lint
        run: yamllint .

      - name: Run chart-testing (lint)
        run: ct lint --config .github/ct/ct.yaml

      - name: Cache kubeconform schemas
        id: cache-powerlint-kubeconform
        uses: actions/cache@0865c47f36e68161719c5b124609996bb5c40129 # tag=v3.0.5
        with:
          path: /tmp
          key: ${{ runner.os }}-powerlint-kubeconform

      - name: Run Powerlint
        env:
          KUBERNETES_VERSIONS: "1.22.0 1.23.0 1.24.0"
        run: chart-powerlint.sh

      # used to test whether the changelog generation process works
      - name: Generate changelogs (test)
        run: generate-chart-changelog.sh

  test:
    runs-on: ubuntu-22.04
    needs:
      - lint
    strategy:
      matrix:
        k8s-version: [1.22.7, 1.23.4, 1.24.0]
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # renovate: tag=v3.0.2
        with:
          fetch-depth: 0

      - name: Set up chart-testing
        uses: helm/chart-testing-action@dae259e86a35ff09145c0805e2d7dd3f7207064a # renovate: tag=v2.2.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@d08cf6ff1575077dee99962540d77ce91c62387d # tag=v1.3.0
        if: steps.list-changed.outputs.changed == 'true'
        with:
          version: v0.13.0
          cluster_name: kind-cluster-k8s-${{ matrix.k8s-version }}
          node_image: kindest/node:v${{ matrix.k8s-version }}

      - name: Run chart-testing (install)
        run: ct install --config .github/ct/install.yaml
