name: Lint and Test Charts

on:
  pull_request:
    branches: [master]

jobs:
  ct-lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --config .github/ct/ct.yaml

  power-lint:
    runs-on: ubuntu-20.04
    container: quay.io/chgl/kube-powertools:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check if documentation is up-to-date
        run: bash scripts/generate-docs.sh && git diff --exit-code HEAD
      - name: Update dependencies
        run: find charts/ ! -path charts/ -maxdepth 1 -type d -exec helm dependency update {} \;
      - name: Run YAML lint
        run: yamllint .
      - name: Run Powerlint
        run: bash scripts/chart-powerlint.sh

  test-in-cluster:
    runs-on: ubuntu-20.04
    needs:
      - ct-lint
      - power-lint
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.1.0

      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v2.0.1
        with:
          config: .github/ct/install.yaml
          command: install
