name: Lint and Test Charts

on:
  pull_request:
    branches: [master]

permissions:
  contents: read

# https://stackoverflow.com/a/72408109
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  lint:
    runs-on: ubuntu-24.04
    container: ghcr.io/chgl/kube-powertools:v2.3.70@sha256:8bf2078f5519fd96872195cc051c473b03488067cfc750a842ac195ff0f64177
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit # change to 'egress-policy: block' after couple of runs
          disable-sudo: true
          disable-telemetry: true

      - name: Add workspace as safe directory
        run: |
          git config --global --add safe.directory /__w/charts/charts

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false

      # via <https://github.com/helm/chart-testing/issues/577>
      - run: |
          git branch "master" "origin/master"

      - name: Check if documentation is up-to-date
        run: |
          generate-docs.sh
          if git diff --exit-code HEAD; then
            echo -e "\033[0;32mDocumentation up to date\033[0m ✔"
          else
            echo -e "\033[0;31mDocumentation outdated! Please run generate-docs.sh locally and push the changes.\033[0m ❌"
            git diff --color
            exit 1
          fi

      - name: Update dependencies
        run: find charts/ ! -path charts/ -maxdepth 1 -type d -exec helm dependency update {} \;

      - name: Run YAML lint
        run: yamllint .

      - name: Run chart-testing (lint)
        run: ct lint --config .github/ct/ct.yaml

      - name: Run ArtifactHub lint
        run: ah lint --kind=helm

      - name: Cache kubeconform schemas
        id: cache-powerlint-kubeconform
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: /tmp
          key: ${{ runner.os }}-powerlint-kubeconform

      - name: Run Powerlint
        env:
          KUBERNETES_VERSIONS: "1.31.0 1.32.0 1.33.0"
        run: chart-powerlint.sh

      # used to test whether the changelog generation process works
      - name: Generate changelogs (test)
        run: generate-chart-changelog.sh

  test:
    runs-on: ubuntu-24.04
    needs:
      - lint
    strategy:
      matrix:
        k8s-version: [1.31.9, 1.32.5, 1.33.2]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit # change to 'egress-policy: block' after couple of runs
          disable-sudo: true
          disable-telemetry: true

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up chart-testing
        uses: helm/chart-testing-action@0d28d3144d3a25ea2cc349d6e59901c4ff469b3b # v2.7.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config .github/ct/install.yaml)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "${GITHUB_OUTPUT}"
          fi

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
        if: ${{steps.list-changed.outputs.changed == 'true'}}
        with:
          cluster_name: kind-cluster-k8s-${{ matrix.k8s-version }}
          node_image: kindest/node:v${{ matrix.k8s-version }}

      - name: Run chart-testing (install)
        if: ${{steps.list-changed.outputs.changed == 'true'}}
        run: ct install --config .github/ct/install.yaml
