name: Lint and Test Charts

on:
  pull_request:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.3

  lint:
    needs:
      - pre-commit
    runs-on: ubuntu-20.04
    container: ghcr.io/chgl/kube-powertools:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check if documentation is up-to-date
        run: generate-docs.sh && git diff --exit-code HEAD

      - name: Update dependencies
        run: find charts/ ! -path charts/ -maxdepth 1 -type d -exec helm dependency update {} \;

      - name: Run YAML lint
        run: yamllint .

      - name: Run chart-testing (lint)
        run: ct lint --config .github/ct/ct.yaml

      - name: Cache kubeconform schemas
        id: cache-powerlint-kubeconform
        uses: actions/cache@v2
        with:
          path: /tmp
          key: ${{ runner.os }}-powerlint-kubeconform

      - name: Run Powerlint
        env:
          # Don't support 1.22 yet since we can't explicitely pass a a Kubernetes version number to
          # `helm template`
          KUBERNETES_VERSIONS: "1.18.0 1.19.0 1.20.0 1.21.0"
        run: chart-powerlint.sh

      # used to test whether the changelog generation process works properly
      - name: Generate changelogs (test)
        run: .github/generate-chart-changelogs.sh

  test:
    runs-on: ubuntu-20.04
    needs:
      - lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: ct install --config .github/ct/install.yaml
