name: Lint and Test Charts

on:
  pull_request:
    branches: [master]

permissions: read-all

jobs:
  lint:
    runs-on: ubuntu-22.04
    container: ghcr.io/chgl/kube-powertools:v2.2.26@sha256:3a7dc917a78f308efeb2db8eb4115f4a3ffe73ed772d3ad11289dd0802c1efd9
    steps:
      - name: Add workspace as safe directory
        run: |
          git config --global --add safe.directory /__w/charts/charts

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      # via <https://github.com/helm/chart-testing/issues/577>
      - run: |
          git branch "master" "origin/master"

      - name: Check if documentation is up-to-date
        run: |
          generate-docs.sh
          if git diff --exit-code HEAD; then
            echo -e "\033[0;32mDocumentation up to date\033[0m ✔"
          else
            echo -e "\033[0;31mDocumentation outdated! Please run generate-docs.sh locally and push the changes.\033[0m ❌"
            git diff --color
            exit 1
          fi

      - name: Update dependencies
        run: find charts/ ! -path charts/ -maxdepth 1 -type d -exec helm dependency update {} \;

      - name: Run YAML lint
        run: yamllint .

      - name: Run chart-testing (lint)
        run: ct lint --config .github/ct/ct.yaml

      - name: Run ArtifactHub lint
        run: ah lint --kind=helm

      - name: Cache kubeconform schemas
        id: cache-powerlint-kubeconform
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        with:
          path: /tmp
          key: ${{ runner.os }}-powerlint-kubeconform

      - name: Run Powerlint
        env:
          KUBERNETES_VERSIONS: "1.26.0 1.27.0 1.28.0"
        run: chart-powerlint.sh

      # used to test whether the changelog generation process works
      - name: Generate changelogs (test)
        run: generate-chart-changelog.sh

  test:
    runs-on: ubuntu-22.04
    needs:
      - lint
    strategy:
      matrix:
        k8s-version: [1.26.6, 1.27.3, 1.28.0]
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Set up chart-testing
        uses: helm/chart-testing-action@e6669bcd63d7cb57cb4380c33043eebe5d111992 # v2.6.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "${GITHUB_OUTPUT}"
          fi

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@dda0770415bac9fc20092cacbc54aa298604d140 # v1.8.0
        if: ${{steps.list-changed.outputs.changed == 'true'}}
        with:
          cluster_name: kind-cluster-k8s-${{ matrix.k8s-version }}
          node_image: kindest/node:v${{ matrix.k8s-version }}

      - name: Run chart-testing (install)
        run: ct install --config .github/ct/install.yaml
