name: Kubescape report

on:
  push:
    branches:
      - master

permissions: read-all

jobs:
  release:
    runs-on: ubuntu-24.04
    container: ghcr.io/chgl/kube-powertools:v2.3.25@sha256:99b5cc7a49cd443fb953ca4ab52dc45245a5c43ad03e3503be06d0d0f512b67d
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Add workspace as safe directory
        run: |
          git config --global --add safe.directory /__w/charts/charts

      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Update dependencies
        run: find charts/ ! -path charts/ -maxdepth 1 -type d -exec helm dependency update {} \;

      - name: Generate kubescape reports
        run: |
          kubescape scan framework cis-v1.23-t1.0.1 --format=html --output=kubescape-reports/cis-v1.23-t1.0.1.html charts/
          kubescape scan framework nsa --format=html --output=kubescape-reports/nsa.html charts/
          kubescape scan framework mitre --format=html --output=kubescape-reports/mitre.html charts/

      - uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
        with:
          add: "kubescape-reports/"
          message: "docs: updated kubescape reports"
          new_branch: gh-pages
          # push: origin HEAD:gh-pages
