name: Check Spelling using cspell
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  spell-check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: npx cspell@5.19.5 lint --gitignore "**/*"
