name: Check Spelling using cspell
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  spell-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # renovate: tag=v3.0.2
      - run: npx cspell@6.1.0 lint --gitignore "**/*"
